default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: ruby_courses_development

test:
  <<: *default
  database: ruby_courses_test

production:
  <<: *default
  database: ruby_courses_production
  username: ruby_courses
  password: <%= ENV['RUBY_COURSES_DATABASE_PASSWORD'] %>
