default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: ruby_courses_development

test:
  <<: *default
  database: ruby_courses_test

production:
  <<: *default
  database: ruby_courses_production
  username: <%= ENV["postgres_username"] %>
  password: <%= ENV["postgres_password_plain"] %>
  host: <%= ENV["postgres_host"] %>
