default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV["db_database"] %>
  username: <%= ENV["db_username"] %>
  password: <%= ENV["db_password_plain"] %>
  host: <%= ENV["db_host"] %>
  pool: <%= ENV["db_pool"] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
