# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c4006dc9132d00134ff54cdeb3a8dbdd188aa9c575d1b8b534c40ad045c57fb37fd9c69459bed015d8f00f17df0aed07393413af645eb9c1112c6ec2e0d80ee

test:
  secret_key_base: 97064366122caf24fd6822f56087f5f7d9720c660d305c71fdc363c2cdfd5a60ef59c56751087ab492de33279faa6fb581c6db5fa38a1e9e32b78ba74aa1e4c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
